builds:
  - main: .
    binary: radio-streamer
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    overrides:
      - goos: darwin
        env:
          - CGO_ENABLED=0
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc
          - PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
